{% set name = "QuShape" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Sargueil-CiTCoM/QuShape

build:
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
    - "cd $({{ PYTHON }} -c 'import os; print(os.path.dirname(os.__file__))') && ln -s site-packages/bsddb3/_pybsddb.so bsddb/_bsddb.so"
    # - "{{ PYTHON }} setup.py install" # --single-version-externally-managed --record=record.txt || exit 1; "
  
requirements:
  host:
    - python =2.7
    - pip
    - gcc 
    - setuptools
  run:
    - python =2.7
    - setuptools
    - pyqt =4
    - numpy
    - matplotlib
    - scipy
    - pip
    - cython
    
#    - bsddb3


about:
  home: https://weekslab.com/software/qushape/
  license: GPL3
  license_family: GPL3
  summary: 
