{% set name = "QuShape" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Sargueil-CiTCoM/QuShape

build:
  number: 0
  script: "{{PYTHON}} -m pip install bsddb3 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python =2.7
    - pip
  run:
    - python =2.7
    - pyqt =4.11.4
    - numpy =1.16.5 
    - matplotlib =2.2
    - scipy =1.2
    - pip
#    - bsddb3


about:
  home: https://weekslab.com/software/qushape/
  license: GPL3
  license_family: GPL3
  summary: 
