{% set name = "QuShape" %}
{% set version = "1.0.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Sargueil-CiTCoM/QuShape
  git_depth: 1

build:
  number: 1
  script: 
    - "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
    # - "{{ PYTHON }} setup.py install" # --single-version-externally-managed --record=record.txt || exit 1; "
  
requirements:
  host:
    - python =2.7
    - pip
    - gcc 
    - setuptools
  run:
    - python =2.7
    - setuptools
    - pyqt =4
    - numpy
    - matplotlib
    - scipy
    - pip
    - cython
    - pyyaml
    
#    - bsddb3


about:
  home: https://weekslab.com/software/qushape/
  license: GPL3
  license_family: GPL3
  summary: 
